[package]
build = "src/build.rs"
name = "diploma"
version = "0.1.0"
edition = "2024"

[dependencies]
rdev = "0.5.3"
slint = "1.11.0"
reqwest = { version = "0.11.27", features = ["json"] }
bcrypt = "0.15"
once_cell = "1.18"

[build-dependencies]
slint-build = "1.11.0"