// authentication/main.slint

import { view, status } from "../global.slint";
import { authorization } from "./authorization.slint";
import { registration } from "./registration.slint";

export component authentication inherits Window
{
    callback authenticate(string, string);
    callback register(string, string);
    callback exit();

    title: "Mandarin Heroes";
    icon: @image-url("../../resources/icons/panda.png");
    width: 380px;
    height: 650px;
    background: #6A5AE0;

    if status.currentView == view.authorization : authorization
    {
        loginClicked(nickName, password) => { root.authenticate(nickName, password); }

        registrationClicked =>
        {
            status.currentView = view.registration;
        }

        exitClicked => { exit(); }
    }

    if status.currentView == view.registration: registration
    {
        performRegistration(nickName, password) => { root.register(nickName, password); }
        authorizationClicked =>
        {
            status.currentView = view.authorization;
        }

        exitClicked => { exit(); }
    }
}